name: Node.js CI/CD

on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]

jobs:
build_and_test:
name: Build and Test
runs-on: ubuntu-latest

strategy:
  matrix:
    node-version: [18.x]

steps:
  # 1. Checkout repository
  - name: Checkout code
    uses: actions/checkout@v3

  # 2. Setup Node.js
  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}

  # 3. Build and test the backend
  - name: Install, Test, and Build Backend
    run: |
      cd backend
      npm install
      npm test
      npm run build

  # 4. Build and test the frontend
  - name: Install, Test, and Build Frontend
    run: |
      cd frontend
      npm install
      npm test
      npm run build
